### ISSUE TITLE
BasicAuth method ISSUE

### ISSUE THREAD

**Issue by ghost** [xFreed0m/ADFSpray#2]
**I tested it and i noticed that there is a problem in Basicauth method
It keeps returning that all credentials are valid, even I checked the target several times.**

**Comment by xFreed0m** [comment]
It doesn't happen for me, can you retry and post the command you used?

**Comment by ghost** [comment]
Hello,

`python3 ADFSpray.py -U myusernames.txt -P  mypasswords.txt -t http://localhost:81 basicauth`

"http://localhost:81" this is a test portal I used so I can test basicauth method on it, but it kept giving me false positives (credentials true in the output, but in reality they are all wrong except one)

Is there a solution?
Thank you so much

**Comment by xFreed0m** [comment]
I can't replicate the issue you are having. Do you have any logs or screenshots to share?

**Comment by ghost** [comment]
Never mind. Thanks for the effort anyways
